name: Autopkg run

on:
  workflow_dispatch: # Manually triggered workflow
    inputs:
      recipe:
        description: Optional recipe to run (e.g. Google/GoogleChrome-test.jamf.recipe.yaml)
        required: false
      debug:
        description: Enable debug mode
        required: false
        default: 'False'
        type: choice
        options:
        - 'False'
        - 'True'

permissions:
  contents: write

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 90
    env:
      AUTOPKG_SHA256: "1944a69aad18b0b9618b48292d115412a98ca165b626f48b11bbc59b504af082"
      AUTOPKG_URL: "https://github.com/autopkg/autopkg/releases/download/v2.7.3/autopkg-2.7.3.pkg"
    
    steps:
    - name: Checkout AutoPkg recipes
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyyaml

    - name: Install AutoPkg
      run: |
        curl -L ${{ env.AUTOPKG_URL }} --output /tmp/autopkg.pkg
        echo "${{ env.AUTOPKG_SHA256 }} */tmp/autopkg.pkg" | shasum -c
        if [[ $? != "0" ]]; then exit 1; fi
        sudo installer -pkg /tmp/autopkg.pkg -target /

    - name: Configure AutoPkg and Git
      run: |
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$(pwd)"/overrides/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
        defaults write com.github.autopkg JAMF_API_USERNAME "${{ secrets.JAMF_API_USERNAME }}"
        defaults write com.github.autopkg JAMF_API_PASSWORD "${{ secrets.JAMF_API_PASSWORD }}"
        defaults write com.github.autopkg JAMF_URL "${{ secrets.JAMF_URL }}"

        defaults write com.github.autopkg API_USERNAME "${{ secrets.JAMF_API_USERNAME }}"
        defaults write com.github.autopkg API_PASSWORD "${{ secrets.JAMF_API_PASSWORD }}"
        defaults write com.github.autopkg JSS_URL "${{ secrets.JAMF_URL }}"
        
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Add AutoPkg repos
      run: |
        for repo in $(cat repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Update AutoPkg Trust Info
      run: |
        for recipe in $(autopkg search . | awk '{print $1}'); do
          autopkg verify-trust-info "$recipe" || autopkg update-trust-info "$recipe"
        done

    - name: Commit Updated Trust Info
      run: |
        git add .
        git commit -m "Updated AutoPkg trust info"
        git push origin main || echo "No changes to commit"

    - name: Run AutoPkg
      run: |
        python3 autopkg_tools.py -l recipe_list.json
        if [ -f pull_request_title ]; then
          echo "TITLE=$(cat pull_request_title)" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat pull_request_body >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi
      env:
        RECIPE: ${{ github.event.inputs.recipe }}

    - name: Create Trust Info Pull Request
      if: env.TITLE
      run: |
        export BRANCH_NAME=trust-info-`date +'%Y-%m-%d'`
        git checkout -b $BRANCH_NAME
        git add overrides/
        git commit -m "${{ env.TITLE }}"
        git push --set-upstream origin $BRANCH_NAME
        jq -n --arg title "${{ env.TITLE }}" \
              --arg body "$BODY" \
              --arg head "$BRANCH_NAME" \
           '{title: $title, body: $body, head: $head, "base": "${{ github.ref }}"}' | curl -s --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/pulls \
           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
           -d@-
